[build]
  base = "/"  # Sets the base directory for the build process, appropriate for your project setup.
  publish = "dist"  # Specifies the output directory where build files will be published.
  command = "npm run build"  # Command to trigger the build process, defined in the project's package.json.

[[redirects]]
  from = "/gsai-webv3/*"  # Redirects any URL that starts with "/gsai-webv3/"
  to = "/gsai-webv3/:splat"  # The ":splat" wildcard captures the remainder of the URL path and applies the redirect.
  status = 301  # Permanent redirect (301) to indicate that the resource has been permanently moved.
  force = true  # Forces this redirect rule to apply even if other conflicting rules exist.
