// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieooitsutkndmtozrrml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllb29pdHN1dGtuZG10b3pycm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjAxMzksImV4cCI6MjA2NTQ5NjEzOX0.EOIPbg1xwF4mbq4jObU8RQj2Wlf6ccUc31rbdBMV3V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);